### ISSUE TITLE
WRITE_MULTIPLE: Illegal Argument: Two operations have different major paths" error

### ISSUE THREAD

**Issue by bizcmd** [oracle/nosql-node-sdk#1]
I'm trying to use the putMany (or writeMany, same problem) function to write more than 1 object row to the table.

SDK version 5.2.  Running on Oracle Cloud Infrastructure NoSQL table called "users", with 50 RU and 5 WU capability.  Permissions set up to manage tables for the user running the script.

I can .put a record OK.  I can .putMany so long as the array is exactly of length 1.  Any more, and it fails with this error:
`NoSQLArgumentError: [ILLEGAL_ARGUMENT] WRITE_MULTIPLE: Illegal Argument: Two operations have different major paths, first: /rP%C2%90/¨000%C2%94 other: /rP%C2%90/¨001x`

Example code:

```

const NoSQLClient = require('oracle-nosqldb').NoSQLClient;
const ServiceType = require('oracle-nosqldb').ServiceType;
const Region = require('oracle-nosqldb').Region;
const Consistency = require('oracle-nosqldb').Consistency;

const main = async() => {

    const client = new NoSQLClient({
        region: Region.UK_LONDON_1,
        serviceType: ServiceType.CLOUD,
        compartment: 'ocid1.compartment......zzz',
        auth: {
            iam: {
                tenantId: 'ocid1.tenancy....ttt',
                userId: 'ocid1.user.uuu',
                fingerprint: '<finbgerprint>',
                privateKeyFile: '<path to pem file>',
                passphrase: '<passphrase here>',
            }
        }
    });

    try {
        const res = await client.putMany('users', [
            {
                user_id: 1,
                name: {
                    first: 'Fred',
                    last: 'Bloggs'
                },
                contact: {
                    email: "fred@bloggs.com"
                }
            },
            {
                user_id: 2,
                name: {
                    first: 'John',
                    last: 'Smith'
                },
                contact: {
                    email: "john@smith.com"
                }
            }
        ]);
        console.log('res from putMany is ', res);
    } catch (err) {
        console.log("ERROR is ", err);
    }

}

main();
```

Appreciate any help here.  The only reference I can find to "Two operations have different major paths" is in this Java file: https://github.com/bantudb/kv/blob/master/src/oracle/kv/impl/api/KVStoreImpl.java

If I comment out the user_id=2 entry, it will run and insert that single entry into the table OK (so I know permissions are OK) but any more than 1 entry and it will generate this error.

Any clues?  Table definition, for reference is show here:
![oracle_table](https://user-images.githubusercontent.com/75837683/102685275-6698dc00-41d7-11eb-9612-54beaab8db5f.jpg)

**Comment by y-polonsk** [comment]
WriteMany operation requires all records to have the same shard key.  Can you provide your table definition here?  If user_id is your primary key and you didn't specify the shard key when creating the table, I believe that the shard key will be the same as primary key, thus the error.  If records have different shard keys they cannot be inserted in an atomic operation.  Please lookup documentation on shard keys and primary keys.

**Comment by y-polonsk** [comment]
Closing the issue due to inactivity.
